// source: fminternal/internal_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.fm.internal.CharacterPersisted');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fm.internal.CharacterPersisted = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fm.internal.CharacterPersisted, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fm.internal.CharacterPersisted.displayName = 'proto.fm.internal.CharacterPersisted';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fm.internal.CharacterPersisted.prototype.toObject = function(opt_includeInstance) {
  return proto.fm.internal.CharacterPersisted.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fm.internal.CharacterPersisted} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fm.internal.CharacterPersisted.toObject = function(includeInstance, msg) {
  var f, obj = {
    characterId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    worldId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    name: jspb.Message.getFieldWithDefault(msg, 3, ""),
    gender: jspb.Message.getFieldWithDefault(msg, 4, 0),
    skinColor: jspb.Message.getFieldWithDefault(msg, 5, 0),
    face: jspb.Message.getFieldWithDefault(msg, 6, 0),
    hair: jspb.Message.getFieldWithDefault(msg, 7, 0),
    level: jspb.Message.getFieldWithDefault(msg, 8, 0),
    classId: jspb.Message.getFieldWithDefault(msg, 9, 0),
    str: jspb.Message.getFieldWithDefault(msg, 10, 0),
    dex: jspb.Message.getFieldWithDefault(msg, 11, 0),
    intStat: jspb.Message.getFieldWithDefault(msg, 12, 0),
    luk: jspb.Message.getFieldWithDefault(msg, 13, 0),
    hp: jspb.Message.getFieldWithDefault(msg, 14, 0),
    maxHp: jspb.Message.getFieldWithDefault(msg, 15, 0),
    mp: jspb.Message.getFieldWithDefault(msg, 16, 0),
    maxMp: jspb.Message.getFieldWithDefault(msg, 17, 0),
    abilityPoint: jspb.Message.getFieldWithDefault(msg, 18, 0),
    exp: jspb.Message.getFieldWithDefault(msg, 19, 0),
    mapId: jspb.Message.getFieldWithDefault(msg, 20, 0),
    spawnPoint: jspb.Message.getFieldWithDefault(msg, 21, 0),
    positionX: jspb.Message.getFieldWithDefault(msg, 22, 0),
    positionY: jspb.Message.getFieldWithDefault(msg, 23, 0),
    stance: jspb.Message.getFieldWithDefault(msg, 24, 0),
    meso: jspb.Message.getFieldWithDefault(msg, 25, 0),
    skillPoint: jspb.Message.getFieldWithDefault(msg, 26, 0),
    accountId: jspb.Message.getFieldWithDefault(msg, 27, 0),
    role: jspb.Message.getFieldWithDefault(msg, 28, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fm.internal.CharacterPersisted}
 */
proto.fm.internal.CharacterPersisted.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fm.internal.CharacterPersisted;
  return proto.fm.internal.CharacterPersisted.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fm.internal.CharacterPersisted} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fm.internal.CharacterPersisted}
 */
proto.fm.internal.CharacterPersisted.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCharacterId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setWorldId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setGender(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSkinColor(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFace(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setHair(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLevel(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setClassId(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setStr(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDex(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setIntStat(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLuk(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setHp(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMaxHp(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMp(value);
      break;
    case 17:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMaxMp(value);
      break;
    case 18:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setAbilityPoint(value);
      break;
    case 19:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setExp(value);
      break;
    case 20:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMapId(value);
      break;
    case 21:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSpawnPoint(value);
      break;
    case 22:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPositionX(value);
      break;
    case 23:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setPositionY(value);
      break;
    case 24:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setStance(value);
      break;
    case 25:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setMeso(value);
      break;
    case 26:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSkillPoint(value);
      break;
    case 27:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setAccountId(value);
      break;
    case 28:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setRole(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fm.internal.CharacterPersisted.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fm.internal.CharacterPersisted.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fm.internal.CharacterPersisted} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fm.internal.CharacterPersisted.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCharacterId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getWorldId();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getGender();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getSkinColor();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getFace();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getHair();
  if (f !== 0) {
    writer.writeUint32(
      7,
      f
    );
  }
  f = message.getLevel();
  if (f !== 0) {
    writer.writeUint32(
      8,
      f
    );
  }
  f = message.getClassId();
  if (f !== 0) {
    writer.writeUint32(
      9,
      f
    );
  }
  f = message.getStr();
  if (f !== 0) {
    writer.writeUint32(
      10,
      f
    );
  }
  f = message.getDex();
  if (f !== 0) {
    writer.writeUint32(
      11,
      f
    );
  }
  f = message.getIntStat();
  if (f !== 0) {
    writer.writeUint32(
      12,
      f
    );
  }
  f = message.getLuk();
  if (f !== 0) {
    writer.writeUint32(
      13,
      f
    );
  }
  f = message.getHp();
  if (f !== 0) {
    writer.writeUint32(
      14,
      f
    );
  }
  f = message.getMaxHp();
  if (f !== 0) {
    writer.writeUint32(
      15,
      f
    );
  }
  f = message.getMp();
  if (f !== 0) {
    writer.writeUint32(
      16,
      f
    );
  }
  f = message.getMaxMp();
  if (f !== 0) {
    writer.writeUint32(
      17,
      f
    );
  }
  f = message.getAbilityPoint();
  if (f !== 0) {
    writer.writeUint32(
      18,
      f
    );
  }
  f = message.getExp();
  if (f !== 0) {
    writer.writeUint32(
      19,
      f
    );
  }
  f = message.getMapId();
  if (f !== 0) {
    writer.writeUint32(
      20,
      f
    );
  }
  f = message.getSpawnPoint();
  if (f !== 0) {
    writer.writeUint32(
      21,
      f
    );
  }
  f = message.getPositionX();
  if (f !== 0) {
    writer.writeInt32(
      22,
      f
    );
  }
  f = message.getPositionY();
  if (f !== 0) {
    writer.writeInt32(
      23,
      f
    );
  }
  f = message.getStance();
  if (f !== 0) {
    writer.writeUint32(
      24,
      f
    );
  }
  f = message.getMeso();
  if (f !== 0) {
    writer.writeInt32(
      25,
      f
    );
  }
  f = message.getSkillPoint();
  if (f !== 0) {
    writer.writeUint32(
      26,
      f
    );
  }
  f = message.getAccountId();
  if (f !== 0) {
    writer.writeUint32(
      27,
      f
    );
  }
  f = message.getRole();
  if (f !== 0) {
    writer.writeUint32(
      28,
      f
    );
  }
};


/**
 * optional uint32 character_id = 1;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getCharacterId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setCharacterId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 world_id = 2;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getWorldId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setWorldId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.fm.internal.CharacterPersisted.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional uint32 gender = 4;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getGender = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setGender = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint32 skin_color = 5;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getSkinColor = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setSkinColor = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional uint32 face = 6;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getFace = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setFace = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional uint32 hair = 7;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getHair = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setHair = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional uint32 level = 8;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getLevel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setLevel = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional uint32 class_id = 9;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getClassId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setClassId = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional uint32 str = 10;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getStr = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setStr = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional uint32 dex = 11;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getDex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setDex = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional uint32 int_stat = 12;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getIntStat = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setIntStat = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional uint32 luk = 13;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getLuk = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setLuk = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * optional uint32 hp = 14;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getHp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setHp = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};


/**
 * optional uint32 max_hp = 15;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getMaxHp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setMaxHp = function(value) {
  return jspb.Message.setProto3IntField(this, 15, value);
};


/**
 * optional uint32 mp = 16;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getMp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setMp = function(value) {
  return jspb.Message.setProto3IntField(this, 16, value);
};


/**
 * optional uint32 max_mp = 17;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getMaxMp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 17, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setMaxMp = function(value) {
  return jspb.Message.setProto3IntField(this, 17, value);
};


/**
 * optional uint32 ability_point = 18;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getAbilityPoint = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 18, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setAbilityPoint = function(value) {
  return jspb.Message.setProto3IntField(this, 18, value);
};


/**
 * optional uint32 exp = 19;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getExp = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 19, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setExp = function(value) {
  return jspb.Message.setProto3IntField(this, 19, value);
};


/**
 * optional uint32 map_id = 20;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getMapId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 20, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setMapId = function(value) {
  return jspb.Message.setProto3IntField(this, 20, value);
};


/**
 * optional uint32 spawn_point = 21;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getSpawnPoint = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 21, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setSpawnPoint = function(value) {
  return jspb.Message.setProto3IntField(this, 21, value);
};


/**
 * optional int32 position_x = 22;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getPositionX = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 22, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setPositionX = function(value) {
  return jspb.Message.setProto3IntField(this, 22, value);
};


/**
 * optional int32 position_y = 23;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getPositionY = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 23, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setPositionY = function(value) {
  return jspb.Message.setProto3IntField(this, 23, value);
};


/**
 * optional uint32 stance = 24;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getStance = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 24, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setStance = function(value) {
  return jspb.Message.setProto3IntField(this, 24, value);
};


/**
 * optional int32 meso = 25;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getMeso = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 25, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setMeso = function(value) {
  return jspb.Message.setProto3IntField(this, 25, value);
};


/**
 * optional uint32 skill_point = 26;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getSkillPoint = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 26, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setSkillPoint = function(value) {
  return jspb.Message.setProto3IntField(this, 26, value);
};


/**
 * optional uint32 account_id = 27;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getAccountId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 27, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setAccountId = function(value) {
  return jspb.Message.setProto3IntField(this, 27, value);
};


/**
 * optional uint32 role = 28;
 * @return {number}
 */
proto.fm.internal.CharacterPersisted.prototype.getRole = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 28, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterPersisted} returns this
 */
proto.fm.internal.CharacterPersisted.prototype.setRole = function(value) {
  return jspb.Message.setProto3IntField(this, 28, value);
};


