// source: fminternal/internal_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.fm.internal.CharacterOverview');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Map');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fm.internal.CharacterOverview = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fm.internal.CharacterOverview, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fm.internal.CharacterOverview.displayName = 'proto.fm.internal.CharacterOverview';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fm.internal.CharacterOverview.prototype.toObject = function(opt_includeInstance) {
  return proto.fm.internal.CharacterOverview.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fm.internal.CharacterOverview} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fm.internal.CharacterOverview.toObject = function(includeInstance, msg) {
  var f, obj = {
    characterId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    name: jspb.Message.getFieldWithDefault(msg, 2, ""),
    gender: jspb.Message.getFieldWithDefault(msg, 3, 0),
    skinColor: jspb.Message.getFieldWithDefault(msg, 4, 0),
    face: jspb.Message.getFieldWithDefault(msg, 5, 0),
    hair: jspb.Message.getFieldWithDefault(msg, 6, 0),
    level: jspb.Message.getFieldWithDefault(msg, 7, 0),
    classId: jspb.Message.getFieldWithDefault(msg, 8, 0),
    mapId: jspb.Message.getFieldWithDefault(msg, 9, 0),
    spawnPoint: jspb.Message.getFieldWithDefault(msg, 10, 0),
    accountId: jspb.Message.getFieldWithDefault(msg, 11, 0),
    worldId: jspb.Message.getFieldWithDefault(msg, 12, 0),
    rank: jspb.Message.getFieldWithDefault(msg, 13, 0),
    rankDiff: jspb.Message.getFieldWithDefault(msg, 14, 0),
    classRank: jspb.Message.getFieldWithDefault(msg, 15, 0),
    classRankDiff: jspb.Message.getFieldWithDefault(msg, 16, 0),
    baseLooksMap: (f = msg.getBaseLooksMap()) ? f.toObject(includeInstance, undefined) : [],
    overlaysMap: (f = msg.getOverlaysMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fm.internal.CharacterOverview}
 */
proto.fm.internal.CharacterOverview.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fm.internal.CharacterOverview;
  return proto.fm.internal.CharacterOverview.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fm.internal.CharacterOverview} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fm.internal.CharacterOverview}
 */
proto.fm.internal.CharacterOverview.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCharacterId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setGender(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSkinColor(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFace(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setHair(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLevel(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setClassId(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMapId(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSpawnPoint(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setAccountId(value);
      break;
    case 12:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setWorldId(value);
      break;
    case 13:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRank(value);
      break;
    case 14:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setRankDiff(value);
      break;
    case 15:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setClassRank(value);
      break;
    case 16:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setClassRankDiff(value);
      break;
    case 17:
      var value = msg.getBaseLooksMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readUint32, null, 0, 0);
         });
      break;
    case 18:
      var value = msg.getOverlaysMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readUint32, null, 0, 0);
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fm.internal.CharacterOverview.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fm.internal.CharacterOverview.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fm.internal.CharacterOverview} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fm.internal.CharacterOverview.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCharacterId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getGender();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getSkinColor();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getFace();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getHair();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getLevel();
  if (f !== 0) {
    writer.writeUint32(
      7,
      f
    );
  }
  f = message.getClassId();
  if (f !== 0) {
    writer.writeUint32(
      8,
      f
    );
  }
  f = message.getMapId();
  if (f !== 0) {
    writer.writeUint32(
      9,
      f
    );
  }
  f = message.getSpawnPoint();
  if (f !== 0) {
    writer.writeUint32(
      10,
      f
    );
  }
  f = message.getAccountId();
  if (f !== 0) {
    writer.writeUint32(
      11,
      f
    );
  }
  f = message.getWorldId();
  if (f !== 0) {
    writer.writeUint32(
      12,
      f
    );
  }
  f = message.getRank();
  if (f !== 0) {
    writer.writeInt32(
      13,
      f
    );
  }
  f = message.getRankDiff();
  if (f !== 0) {
    writer.writeInt32(
      14,
      f
    );
  }
  f = message.getClassRank();
  if (f !== 0) {
    writer.writeInt32(
      15,
      f
    );
  }
  f = message.getClassRankDiff();
  if (f !== 0) {
    writer.writeInt32(
      16,
      f
    );
  }
  f = message.getBaseLooksMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(17, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeUint32);
  }
  f = message.getOverlaysMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(18, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeUint32);
  }
};


/**
 * optional uint32 character_id = 1;
 * @return {number}
 */
proto.fm.internal.CharacterOverview.prototype.getCharacterId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterOverview} returns this
 */
proto.fm.internal.CharacterOverview.prototype.setCharacterId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string name = 2;
 * @return {string}
 */
proto.fm.internal.CharacterOverview.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.fm.internal.CharacterOverview} returns this
 */
proto.fm.internal.CharacterOverview.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional uint32 gender = 3;
 * @return {number}
 */
proto.fm.internal.CharacterOverview.prototype.getGender = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterOverview} returns this
 */
proto.fm.internal.CharacterOverview.prototype.setGender = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 skin_color = 4;
 * @return {number}
 */
proto.fm.internal.CharacterOverview.prototype.getSkinColor = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterOverview} returns this
 */
proto.fm.internal.CharacterOverview.prototype.setSkinColor = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint32 face = 5;
 * @return {number}
 */
proto.fm.internal.CharacterOverview.prototype.getFace = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterOverview} returns this
 */
proto.fm.internal.CharacterOverview.prototype.setFace = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional uint32 hair = 6;
 * @return {number}
 */
proto.fm.internal.CharacterOverview.prototype.getHair = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterOverview} returns this
 */
proto.fm.internal.CharacterOverview.prototype.setHair = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional uint32 level = 7;
 * @return {number}
 */
proto.fm.internal.CharacterOverview.prototype.getLevel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterOverview} returns this
 */
proto.fm.internal.CharacterOverview.prototype.setLevel = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional uint32 class_id = 8;
 * @return {number}
 */
proto.fm.internal.CharacterOverview.prototype.getClassId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterOverview} returns this
 */
proto.fm.internal.CharacterOverview.prototype.setClassId = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional uint32 map_id = 9;
 * @return {number}
 */
proto.fm.internal.CharacterOverview.prototype.getMapId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterOverview} returns this
 */
proto.fm.internal.CharacterOverview.prototype.setMapId = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional uint32 spawn_point = 10;
 * @return {number}
 */
proto.fm.internal.CharacterOverview.prototype.getSpawnPoint = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterOverview} returns this
 */
proto.fm.internal.CharacterOverview.prototype.setSpawnPoint = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional uint32 account_id = 11;
 * @return {number}
 */
proto.fm.internal.CharacterOverview.prototype.getAccountId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterOverview} returns this
 */
proto.fm.internal.CharacterOverview.prototype.setAccountId = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional uint32 world_id = 12;
 * @return {number}
 */
proto.fm.internal.CharacterOverview.prototype.getWorldId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 12, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterOverview} returns this
 */
proto.fm.internal.CharacterOverview.prototype.setWorldId = function(value) {
  return jspb.Message.setProto3IntField(this, 12, value);
};


/**
 * optional int32 rank = 13;
 * @return {number}
 */
proto.fm.internal.CharacterOverview.prototype.getRank = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 13, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterOverview} returns this
 */
proto.fm.internal.CharacterOverview.prototype.setRank = function(value) {
  return jspb.Message.setProto3IntField(this, 13, value);
};


/**
 * optional int32 rank_diff = 14;
 * @return {number}
 */
proto.fm.internal.CharacterOverview.prototype.getRankDiff = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 14, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterOverview} returns this
 */
proto.fm.internal.CharacterOverview.prototype.setRankDiff = function(value) {
  return jspb.Message.setProto3IntField(this, 14, value);
};


/**
 * optional int32 class_rank = 15;
 * @return {number}
 */
proto.fm.internal.CharacterOverview.prototype.getClassRank = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 15, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterOverview} returns this
 */
proto.fm.internal.CharacterOverview.prototype.setClassRank = function(value) {
  return jspb.Message.setProto3IntField(this, 15, value);
};


/**
 * optional int32 class_rank_diff = 16;
 * @return {number}
 */
proto.fm.internal.CharacterOverview.prototype.getClassRankDiff = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 16, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CharacterOverview} returns this
 */
proto.fm.internal.CharacterOverview.prototype.setClassRankDiff = function(value) {
  return jspb.Message.setProto3IntField(this, 16, value);
};


/**
 * map<int32, uint32> base_looks = 17;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,number>}
 */
proto.fm.internal.CharacterOverview.prototype.getBaseLooksMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,number>} */ (
      jspb.Message.getMapField(this, 17, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.fm.internal.CharacterOverview} returns this
 */
proto.fm.internal.CharacterOverview.prototype.clearBaseLooksMap = function() {
  this.getBaseLooksMap().clear();
  return this;};


/**
 * map<int32, uint32> overlays = 18;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,number>}
 */
proto.fm.internal.CharacterOverview.prototype.getOverlaysMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,number>} */ (
      jspb.Message.getMapField(this, 18, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.fm.internal.CharacterOverview} returns this
 */
proto.fm.internal.CharacterOverview.prototype.clearOverlaysMap = function() {
  this.getOverlaysMap().clear();
  return this;};


