// source: fminternal/internal_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.fm.internal.CreateCharacterRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fm.internal.CreateCharacterRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fm.internal.CreateCharacterRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fm.internal.CreateCharacterRequest.displayName = 'proto.fm.internal.CreateCharacterRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fm.internal.CreateCharacterRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.fm.internal.CreateCharacterRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fm.internal.CreateCharacterRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fm.internal.CreateCharacterRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    accountId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    worldId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    name: jspb.Message.getFieldWithDefault(msg, 3, ""),
    face: jspb.Message.getFieldWithDefault(msg, 4, 0),
    hair: jspb.Message.getFieldWithDefault(msg, 5, 0),
    skinColor: jspb.Message.getFieldWithDefault(msg, 6, 0),
    topItemId: jspb.Message.getFieldWithDefault(msg, 7, 0),
    bottomItemId: jspb.Message.getFieldWithDefault(msg, 8, 0),
    shoesItemId: jspb.Message.getFieldWithDefault(msg, 9, 0),
    weaponItemId: jspb.Message.getFieldWithDefault(msg, 10, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fm.internal.CreateCharacterRequest}
 */
proto.fm.internal.CreateCharacterRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fm.internal.CreateCharacterRequest;
  return proto.fm.internal.CreateCharacterRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fm.internal.CreateCharacterRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fm.internal.CreateCharacterRequest}
 */
proto.fm.internal.CreateCharacterRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setAccountId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setWorldId(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFace(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setHair(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setSkinColor(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setTopItemId(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setBottomItemId(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setShoesItemId(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setWeaponItemId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fm.internal.CreateCharacterRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fm.internal.CreateCharacterRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fm.internal.CreateCharacterRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fm.internal.CreateCharacterRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAccountId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getWorldId();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getFace();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getHair();
  if (f !== 0) {
    writer.writeUint32(
      5,
      f
    );
  }
  f = message.getSkinColor();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getTopItemId();
  if (f !== 0) {
    writer.writeUint32(
      7,
      f
    );
  }
  f = message.getBottomItemId();
  if (f !== 0) {
    writer.writeUint32(
      8,
      f
    );
  }
  f = message.getShoesItemId();
  if (f !== 0) {
    writer.writeUint32(
      9,
      f
    );
  }
  f = message.getWeaponItemId();
  if (f !== 0) {
    writer.writeUint32(
      10,
      f
    );
  }
};


/**
 * optional uint32 account_id = 1;
 * @return {number}
 */
proto.fm.internal.CreateCharacterRequest.prototype.getAccountId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CreateCharacterRequest} returns this
 */
proto.fm.internal.CreateCharacterRequest.prototype.setAccountId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 world_id = 2;
 * @return {number}
 */
proto.fm.internal.CreateCharacterRequest.prototype.getWorldId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CreateCharacterRequest} returns this
 */
proto.fm.internal.CreateCharacterRequest.prototype.setWorldId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.fm.internal.CreateCharacterRequest.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.fm.internal.CreateCharacterRequest} returns this
 */
proto.fm.internal.CreateCharacterRequest.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional uint32 face = 4;
 * @return {number}
 */
proto.fm.internal.CreateCharacterRequest.prototype.getFace = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CreateCharacterRequest} returns this
 */
proto.fm.internal.CreateCharacterRequest.prototype.setFace = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional uint32 hair = 5;
 * @return {number}
 */
proto.fm.internal.CreateCharacterRequest.prototype.getHair = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CreateCharacterRequest} returns this
 */
proto.fm.internal.CreateCharacterRequest.prototype.setHair = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional uint32 skin_color = 6;
 * @return {number}
 */
proto.fm.internal.CreateCharacterRequest.prototype.getSkinColor = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CreateCharacterRequest} returns this
 */
proto.fm.internal.CreateCharacterRequest.prototype.setSkinColor = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional uint32 top_item_id = 7;
 * @return {number}
 */
proto.fm.internal.CreateCharacterRequest.prototype.getTopItemId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CreateCharacterRequest} returns this
 */
proto.fm.internal.CreateCharacterRequest.prototype.setTopItemId = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional uint32 bottom_item_id = 8;
 * @return {number}
 */
proto.fm.internal.CreateCharacterRequest.prototype.getBottomItemId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CreateCharacterRequest} returns this
 */
proto.fm.internal.CreateCharacterRequest.prototype.setBottomItemId = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional uint32 shoes_item_id = 9;
 * @return {number}
 */
proto.fm.internal.CreateCharacterRequest.prototype.getShoesItemId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CreateCharacterRequest} returns this
 */
proto.fm.internal.CreateCharacterRequest.prototype.setShoesItemId = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional uint32 weapon_item_id = 10;
 * @return {number}
 */
proto.fm.internal.CreateCharacterRequest.prototype.getWeaponItemId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.CreateCharacterRequest} returns this
 */
proto.fm.internal.CreateCharacterRequest.prototype.setWeaponItemId = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


