// source: fminternal/internal_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.fm.internal.LoginAccountReply');
goog.provide('proto.fm.internal.LoginAccountReply.Status');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fm.internal.LoginAccountReply = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fm.internal.LoginAccountReply, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fm.internal.LoginAccountReply.displayName = 'proto.fm.internal.LoginAccountReply';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fm.internal.LoginAccountReply.prototype.toObject = function(opt_includeInstance) {
  return proto.fm.internal.LoginAccountReply.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fm.internal.LoginAccountReply} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fm.internal.LoginAccountReply.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: jspb.Message.getFieldWithDefault(msg, 1, 0),
    accountId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    gender: jspb.Message.getFieldWithDefault(msg, 3, 0),
    isChatBlocked: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    chatBlockedUntilUnixMs: jspb.Message.getFieldWithDefault(msg, 5, 0),
    characterSlotCount: jspb.Message.getFieldWithDefault(msg, 6, 0),
    role: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fm.internal.LoginAccountReply}
 */
proto.fm.internal.LoginAccountReply.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fm.internal.LoginAccountReply;
  return proto.fm.internal.LoginAccountReply.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fm.internal.LoginAccountReply} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fm.internal.LoginAccountReply}
 */
proto.fm.internal.LoginAccountReply.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.fm.internal.LoginAccountReply.Status} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setAccountId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setGender(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsChatBlocked(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setChatBlockedUntilUnixMs(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCharacterSlotCount(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setRole(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fm.internal.LoginAccountReply.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fm.internal.LoginAccountReply.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fm.internal.LoginAccountReply} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fm.internal.LoginAccountReply.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getAccountId();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getGender();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getIsChatBlocked();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getChatBlockedUntilUnixMs();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getCharacterSlotCount();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = message.getRole();
  if (f !== 0) {
    writer.writeUint32(
      7,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.fm.internal.LoginAccountReply.Status = {
  SUCCESS: 0,
  WRONG_PASSWORD: 1,
  BANNED: 2,
  REGISTERED: 3,
  ALREADY_LOGGED_IN: 4
};

/**
 * optional Status status = 1;
 * @return {!proto.fm.internal.LoginAccountReply.Status}
 */
proto.fm.internal.LoginAccountReply.prototype.getStatus = function() {
  return /** @type {!proto.fm.internal.LoginAccountReply.Status} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.fm.internal.LoginAccountReply.Status} value
 * @return {!proto.fm.internal.LoginAccountReply} returns this
 */
proto.fm.internal.LoginAccountReply.prototype.setStatus = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional uint32 account_id = 2;
 * @return {number}
 */
proto.fm.internal.LoginAccountReply.prototype.getAccountId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.LoginAccountReply} returns this
 */
proto.fm.internal.LoginAccountReply.prototype.setAccountId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 gender = 3;
 * @return {number}
 */
proto.fm.internal.LoginAccountReply.prototype.getGender = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.LoginAccountReply} returns this
 */
proto.fm.internal.LoginAccountReply.prototype.setGender = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional bool is_chat_blocked = 4;
 * @return {boolean}
 */
proto.fm.internal.LoginAccountReply.prototype.getIsChatBlocked = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.fm.internal.LoginAccountReply} returns this
 */
proto.fm.internal.LoginAccountReply.prototype.setIsChatBlocked = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional int64 chat_blocked_until_unix_ms = 5;
 * @return {number}
 */
proto.fm.internal.LoginAccountReply.prototype.getChatBlockedUntilUnixMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.LoginAccountReply} returns this
 */
proto.fm.internal.LoginAccountReply.prototype.setChatBlockedUntilUnixMs = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional uint32 character_slot_count = 6;
 * @return {number}
 */
proto.fm.internal.LoginAccountReply.prototype.getCharacterSlotCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.LoginAccountReply} returns this
 */
proto.fm.internal.LoginAccountReply.prototype.setCharacterSlotCount = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional uint32 role = 7;
 * @return {number}
 */
proto.fm.internal.LoginAccountReply.prototype.getRole = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.LoginAccountReply} returns this
 */
proto.fm.internal.LoginAccountReply.prototype.setRole = function(value) {
  return jspb.Message.setProto3IntField(this, 7, value);
};


