// source: fminternal/internal_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.fm.internal.PartyMemberSnapshot');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fm.internal.PartyMemberSnapshot = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fm.internal.PartyMemberSnapshot, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fm.internal.PartyMemberSnapshot.displayName = 'proto.fm.internal.PartyMemberSnapshot';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fm.internal.PartyMemberSnapshot.prototype.toObject = function(opt_includeInstance) {
  return proto.fm.internal.PartyMemberSnapshot.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fm.internal.PartyMemberSnapshot} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fm.internal.PartyMemberSnapshot.toObject = function(includeInstance, msg) {
  var f, obj = {
    characterId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    characterName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    level: jspb.Message.getFieldWithDefault(msg, 3, 0),
    classId: jspb.Message.getFieldWithDefault(msg, 4, 0),
    role: jspb.Message.getFieldWithDefault(msg, 5, ""),
    mapId: jspb.Message.getFieldWithDefault(msg, 6, 0),
    channelIndex: jspb.Message.getFieldWithDefault(msg, 7, 0),
    doorTown: jspb.Message.getFieldWithDefault(msg, 8, 0),
    doorTarget: jspb.Message.getFieldWithDefault(msg, 9, 0),
    doorX: jspb.Message.getFieldWithDefault(msg, 10, 0),
    doorY: jspb.Message.getFieldWithDefault(msg, 11, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fm.internal.PartyMemberSnapshot}
 */
proto.fm.internal.PartyMemberSnapshot.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fm.internal.PartyMemberSnapshot;
  return proto.fm.internal.PartyMemberSnapshot.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fm.internal.PartyMemberSnapshot} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fm.internal.PartyMemberSnapshot}
 */
proto.fm.internal.PartyMemberSnapshot.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setCharacterId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setCharacterName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLevel(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setClassId(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setRole(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setMapId(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setChannelIndex(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDoorTown(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setDoorTarget(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDoorX(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDoorY(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fm.internal.PartyMemberSnapshot.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fm.internal.PartyMemberSnapshot.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fm.internal.PartyMemberSnapshot} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fm.internal.PartyMemberSnapshot.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCharacterId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getCharacterName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getLevel();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getClassId();
  if (f !== 0) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = message.getRole();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getMapId();
  if (f !== 0) {
    writer.writeUint32(
      6,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 7));
  if (f != null) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getDoorTown();
  if (f !== 0) {
    writer.writeUint32(
      8,
      f
    );
  }
  f = message.getDoorTarget();
  if (f !== 0) {
    writer.writeUint32(
      9,
      f
    );
  }
  f = message.getDoorX();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getDoorY();
  if (f !== 0) {
    writer.writeInt32(
      11,
      f
    );
  }
};


/**
 * optional uint32 character_id = 1;
 * @return {number}
 */
proto.fm.internal.PartyMemberSnapshot.prototype.getCharacterId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.PartyMemberSnapshot} returns this
 */
proto.fm.internal.PartyMemberSnapshot.prototype.setCharacterId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string character_name = 2;
 * @return {string}
 */
proto.fm.internal.PartyMemberSnapshot.prototype.getCharacterName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.fm.internal.PartyMemberSnapshot} returns this
 */
proto.fm.internal.PartyMemberSnapshot.prototype.setCharacterName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional uint32 level = 3;
 * @return {number}
 */
proto.fm.internal.PartyMemberSnapshot.prototype.getLevel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.PartyMemberSnapshot} returns this
 */
proto.fm.internal.PartyMemberSnapshot.prototype.setLevel = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint32 class_id = 4;
 * @return {number}
 */
proto.fm.internal.PartyMemberSnapshot.prototype.getClassId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.PartyMemberSnapshot} returns this
 */
proto.fm.internal.PartyMemberSnapshot.prototype.setClassId = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string role = 5;
 * @return {string}
 */
proto.fm.internal.PartyMemberSnapshot.prototype.getRole = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.fm.internal.PartyMemberSnapshot} returns this
 */
proto.fm.internal.PartyMemberSnapshot.prototype.setRole = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional uint32 map_id = 6;
 * @return {number}
 */
proto.fm.internal.PartyMemberSnapshot.prototype.getMapId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.PartyMemberSnapshot} returns this
 */
proto.fm.internal.PartyMemberSnapshot.prototype.setMapId = function(value) {
  return jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int32 channel_index = 7;
 * @return {number}
 */
proto.fm.internal.PartyMemberSnapshot.prototype.getChannelIndex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.PartyMemberSnapshot} returns this
 */
proto.fm.internal.PartyMemberSnapshot.prototype.setChannelIndex = function(value) {
  return jspb.Message.setField(this, 7, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.fm.internal.PartyMemberSnapshot} returns this
 */
proto.fm.internal.PartyMemberSnapshot.prototype.clearChannelIndex = function() {
  return jspb.Message.setField(this, 7, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.fm.internal.PartyMemberSnapshot.prototype.hasChannelIndex = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional uint32 door_town = 8;
 * @return {number}
 */
proto.fm.internal.PartyMemberSnapshot.prototype.getDoorTown = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.PartyMemberSnapshot} returns this
 */
proto.fm.internal.PartyMemberSnapshot.prototype.setDoorTown = function(value) {
  return jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional uint32 door_target = 9;
 * @return {number}
 */
proto.fm.internal.PartyMemberSnapshot.prototype.getDoorTarget = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.PartyMemberSnapshot} returns this
 */
proto.fm.internal.PartyMemberSnapshot.prototype.setDoorTarget = function(value) {
  return jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional int32 door_x = 10;
 * @return {number}
 */
proto.fm.internal.PartyMemberSnapshot.prototype.getDoorX = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.PartyMemberSnapshot} returns this
 */
proto.fm.internal.PartyMemberSnapshot.prototype.setDoorX = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional int32 door_y = 11;
 * @return {number}
 */
proto.fm.internal.PartyMemberSnapshot.prototype.getDoorY = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.PartyMemberSnapshot} returns this
 */
proto.fm.internal.PartyMemberSnapshot.prototype.setDoorY = function(value) {
  return jspb.Message.setProto3IntField(this, 11, value);
};


