// source: fminternal/internal_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.fm.internal.PartySnapshot');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.fm.internal.PartyMemberSnapshot');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fm.internal.PartySnapshot = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.fm.internal.PartySnapshot.repeatedFields_, null);
};
goog.inherits(proto.fm.internal.PartySnapshot, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fm.internal.PartySnapshot.displayName = 'proto.fm.internal.PartySnapshot';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.fm.internal.PartySnapshot.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fm.internal.PartySnapshot.prototype.toObject = function(opt_includeInstance) {
  return proto.fm.internal.PartySnapshot.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fm.internal.PartySnapshot} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fm.internal.PartySnapshot.toObject = function(includeInstance, msg) {
  var f, obj = {
    worldId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    partyId: jspb.Message.getFieldWithDefault(msg, 2, 0),
    leaderCharacterId: jspb.Message.getFieldWithDefault(msg, 3, 0),
    revision: jspb.Message.getFieldWithDefault(msg, 4, 0),
    state: jspb.Message.getFieldWithDefault(msg, 5, ""),
    membersList: jspb.Message.toObjectList(msg.getMembersList(),
    proto.fm.internal.PartyMemberSnapshot.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fm.internal.PartySnapshot}
 */
proto.fm.internal.PartySnapshot.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fm.internal.PartySnapshot;
  return proto.fm.internal.PartySnapshot.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fm.internal.PartySnapshot} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fm.internal.PartySnapshot}
 */
proto.fm.internal.PartySnapshot.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setWorldId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPartyId(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setLeaderCharacterId(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint64());
      msg.setRevision(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setState(value);
      break;
    case 6:
      var value = new proto.fm.internal.PartyMemberSnapshot;
      reader.readMessage(value,proto.fm.internal.PartyMemberSnapshot.deserializeBinaryFromReader);
      msg.addMembers(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fm.internal.PartySnapshot.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fm.internal.PartySnapshot.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fm.internal.PartySnapshot} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fm.internal.PartySnapshot.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWorldId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getPartyId();
  if (f !== 0) {
    writer.writeUint32(
      2,
      f
    );
  }
  f = message.getLeaderCharacterId();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getRevision();
  if (f !== 0) {
    writer.writeUint64(
      4,
      f
    );
  }
  f = message.getState();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getMembersList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.fm.internal.PartyMemberSnapshot.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 world_id = 1;
 * @return {number}
 */
proto.fm.internal.PartySnapshot.prototype.getWorldId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.PartySnapshot} returns this
 */
proto.fm.internal.PartySnapshot.prototype.setWorldId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional uint32 party_id = 2;
 * @return {number}
 */
proto.fm.internal.PartySnapshot.prototype.getPartyId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.PartySnapshot} returns this
 */
proto.fm.internal.PartySnapshot.prototype.setPartyId = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional uint32 leader_character_id = 3;
 * @return {number}
 */
proto.fm.internal.PartySnapshot.prototype.getLeaderCharacterId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.PartySnapshot} returns this
 */
proto.fm.internal.PartySnapshot.prototype.setLeaderCharacterId = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional uint64 revision = 4;
 * @return {number}
 */
proto.fm.internal.PartySnapshot.prototype.getRevision = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.PartySnapshot} returns this
 */
proto.fm.internal.PartySnapshot.prototype.setRevision = function(value) {
  return jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string state = 5;
 * @return {string}
 */
proto.fm.internal.PartySnapshot.prototype.getState = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.fm.internal.PartySnapshot} returns this
 */
proto.fm.internal.PartySnapshot.prototype.setState = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * repeated PartyMemberSnapshot members = 6;
 * @return {!Array<!proto.fm.internal.PartyMemberSnapshot>}
 */
proto.fm.internal.PartySnapshot.prototype.getMembersList = function() {
  return /** @type{!Array<!proto.fm.internal.PartyMemberSnapshot>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.fm.internal.PartyMemberSnapshot, 6));
};


/**
 * @param {!Array<!proto.fm.internal.PartyMemberSnapshot>} value
 * @return {!proto.fm.internal.PartySnapshot} returns this
*/
proto.fm.internal.PartySnapshot.prototype.setMembersList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.fm.internal.PartyMemberSnapshot=} opt_value
 * @param {number=} opt_index
 * @return {!proto.fm.internal.PartyMemberSnapshot}
 */
proto.fm.internal.PartySnapshot.prototype.addMembers = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.fm.internal.PartyMemberSnapshot, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.fm.internal.PartySnapshot} returns this
 */
proto.fm.internal.PartySnapshot.prototype.clearMembersList = function() {
  return this.setMembersList([]);
};


