// source: fminternal/internal_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.fm.internal.SaveCharacterRequest');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Map');
goog.require('jspb.Message');
goog.require('proto.fm.internal.CharacterPersisted');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fm.internal.SaveCharacterRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.fm.internal.SaveCharacterRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fm.internal.SaveCharacterRequest.displayName = 'proto.fm.internal.SaveCharacterRequest';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fm.internal.SaveCharacterRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.fm.internal.SaveCharacterRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fm.internal.SaveCharacterRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fm.internal.SaveCharacterRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    character: (f = msg.getCharacter()) && proto.fm.internal.CharacterPersisted.toObject(includeInstance, f),
    baseLooksMap: (f = msg.getBaseLooksMap()) ? f.toObject(includeInstance, undefined) : [],
    overlaysMap: (f = msg.getOverlaysMap()) ? f.toObject(includeInstance, undefined) : []
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fm.internal.SaveCharacterRequest}
 */
proto.fm.internal.SaveCharacterRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fm.internal.SaveCharacterRequest;
  return proto.fm.internal.SaveCharacterRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fm.internal.SaveCharacterRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fm.internal.SaveCharacterRequest}
 */
proto.fm.internal.SaveCharacterRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.fm.internal.CharacterPersisted;
      reader.readMessage(value,proto.fm.internal.CharacterPersisted.deserializeBinaryFromReader);
      msg.setCharacter(value);
      break;
    case 2:
      var value = msg.getBaseLooksMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readUint32, null, 0, 0);
         });
      break;
    case 3:
      var value = msg.getOverlaysMap();
      reader.readMessage(value, function(message, reader) {
        jspb.Map.deserializeBinary(message, reader, jspb.BinaryReader.prototype.readInt32, jspb.BinaryReader.prototype.readUint32, null, 0, 0);
         });
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fm.internal.SaveCharacterRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fm.internal.SaveCharacterRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fm.internal.SaveCharacterRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fm.internal.SaveCharacterRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCharacter();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.fm.internal.CharacterPersisted.serializeBinaryToWriter
    );
  }
  f = message.getBaseLooksMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(2, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeUint32);
  }
  f = message.getOverlaysMap(true);
  if (f && f.getLength() > 0) {
    f.serializeBinary(3, writer, jspb.BinaryWriter.prototype.writeInt32, jspb.BinaryWriter.prototype.writeUint32);
  }
};


/**
 * optional CharacterPersisted character = 1;
 * @return {?proto.fm.internal.CharacterPersisted}
 */
proto.fm.internal.SaveCharacterRequest.prototype.getCharacter = function() {
  return /** @type{?proto.fm.internal.CharacterPersisted} */ (
    jspb.Message.getWrapperField(this, proto.fm.internal.CharacterPersisted, 1));
};


/**
 * @param {?proto.fm.internal.CharacterPersisted|undefined} value
 * @return {!proto.fm.internal.SaveCharacterRequest} returns this
*/
proto.fm.internal.SaveCharacterRequest.prototype.setCharacter = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.fm.internal.SaveCharacterRequest} returns this
 */
proto.fm.internal.SaveCharacterRequest.prototype.clearCharacter = function() {
  return this.setCharacter(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.fm.internal.SaveCharacterRequest.prototype.hasCharacter = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * map<int32, uint32> base_looks = 2;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,number>}
 */
proto.fm.internal.SaveCharacterRequest.prototype.getBaseLooksMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,number>} */ (
      jspb.Message.getMapField(this, 2, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.fm.internal.SaveCharacterRequest} returns this
 */
proto.fm.internal.SaveCharacterRequest.prototype.clearBaseLooksMap = function() {
  this.getBaseLooksMap().clear();
  return this;};


/**
 * map<int32, uint32> overlays = 3;
 * @param {boolean=} opt_noLazyCreate Do not create the map if
 * empty, instead returning `undefined`
 * @return {!jspb.Map<number,number>}
 */
proto.fm.internal.SaveCharacterRequest.prototype.getOverlaysMap = function(opt_noLazyCreate) {
  return /** @type {!jspb.Map<number,number>} */ (
      jspb.Message.getMapField(this, 3, opt_noLazyCreate,
      null));
};


/**
 * Clears values from the map. The map will be non-null.
 * @return {!proto.fm.internal.SaveCharacterRequest} returns this
 */
proto.fm.internal.SaveCharacterRequest.prototype.clearOverlaysMap = function() {
  this.getOverlaysMap().clear();
  return this;};


