// source: fminternal/internal_service.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

goog.provide('proto.fm.internal.WorldCatalog');

goog.require('jspb.BinaryReader');
goog.require('jspb.BinaryWriter');
goog.require('jspb.Message');
goog.require('proto.fm.internal.ChannelCatalog');

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.fm.internal.WorldCatalog = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.fm.internal.WorldCatalog.repeatedFields_, null);
};
goog.inherits(proto.fm.internal.WorldCatalog, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.fm.internal.WorldCatalog.displayName = 'proto.fm.internal.WorldCatalog';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.fm.internal.WorldCatalog.repeatedFields_ = [5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.fm.internal.WorldCatalog.prototype.toObject = function(opt_includeInstance) {
  return proto.fm.internal.WorldCatalog.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.fm.internal.WorldCatalog} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fm.internal.WorldCatalog.toObject = function(includeInstance, msg) {
  var f, obj = {
    worldId: jspb.Message.getFieldWithDefault(msg, 1, 0),
    worldName: jspb.Message.getFieldWithDefault(msg, 2, ""),
    flag: jspb.Message.getFieldWithDefault(msg, 3, 0),
    eventMessage: jspb.Message.getFieldWithDefault(msg, 4, ""),
    channelsList: jspb.Message.toObjectList(msg.getChannelsList(),
    proto.fm.internal.ChannelCatalog.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.fm.internal.WorldCatalog}
 */
proto.fm.internal.WorldCatalog.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.fm.internal.WorldCatalog;
  return proto.fm.internal.WorldCatalog.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.fm.internal.WorldCatalog} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.fm.internal.WorldCatalog}
 */
proto.fm.internal.WorldCatalog.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setWorldId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setWorldName(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setFlag(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setEventMessage(value);
      break;
    case 5:
      var value = new proto.fm.internal.ChannelCatalog;
      reader.readMessage(value,proto.fm.internal.ChannelCatalog.deserializeBinaryFromReader);
      msg.addChannels(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.fm.internal.WorldCatalog.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.fm.internal.WorldCatalog.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.fm.internal.WorldCatalog} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.fm.internal.WorldCatalog.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWorldId();
  if (f !== 0) {
    writer.writeUint32(
      1,
      f
    );
  }
  f = message.getWorldName();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getFlag();
  if (f !== 0) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = message.getEventMessage();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getChannelsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.fm.internal.ChannelCatalog.serializeBinaryToWriter
    );
  }
};


/**
 * optional uint32 world_id = 1;
 * @return {number}
 */
proto.fm.internal.WorldCatalog.prototype.getWorldId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.WorldCatalog} returns this
 */
proto.fm.internal.WorldCatalog.prototype.setWorldId = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional string world_name = 2;
 * @return {string}
 */
proto.fm.internal.WorldCatalog.prototype.getWorldName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.fm.internal.WorldCatalog} returns this
 */
proto.fm.internal.WorldCatalog.prototype.setWorldName = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional uint32 flag = 3;
 * @return {number}
 */
proto.fm.internal.WorldCatalog.prototype.getFlag = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.fm.internal.WorldCatalog} returns this
 */
proto.fm.internal.WorldCatalog.prototype.setFlag = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string event_message = 4;
 * @return {string}
 */
proto.fm.internal.WorldCatalog.prototype.getEventMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * @param {string} value
 * @return {!proto.fm.internal.WorldCatalog} returns this
 */
proto.fm.internal.WorldCatalog.prototype.setEventMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * repeated ChannelCatalog channels = 5;
 * @return {!Array<!proto.fm.internal.ChannelCatalog>}
 */
proto.fm.internal.WorldCatalog.prototype.getChannelsList = function() {
  return /** @type{!Array<!proto.fm.internal.ChannelCatalog>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.fm.internal.ChannelCatalog, 5));
};


/**
 * @param {!Array<!proto.fm.internal.ChannelCatalog>} value
 * @return {!proto.fm.internal.WorldCatalog} returns this
*/
proto.fm.internal.WorldCatalog.prototype.setChannelsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.fm.internal.ChannelCatalog=} opt_value
 * @param {number=} opt_index
 * @return {!proto.fm.internal.ChannelCatalog}
 */
proto.fm.internal.WorldCatalog.prototype.addChannels = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.fm.internal.ChannelCatalog, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.fm.internal.WorldCatalog} returns this
 */
proto.fm.internal.WorldCatalog.prototype.clearChannelsList = function() {
  return this.setChannelsList([]);
};


