register_test("login_smoke")
register_test("npc_dialog")
register_test("channel_transfer")
register_test("combat_smoke")
register_test("reactor_smoke")
register_test("portal_subway", { serial = true })
register_test("kerning_pq", { serial = true, timeout_ms = 600000 })
register_test("carnival_1v1", { serial = true, timeout_ms = 600000 })
register_test("ludibrium_pq", { serial = true, timeout_ms = 1200000 })
register_test("orbis_pq", { serial = true, timeout_ms = 1800000 })
register_test("henesys_pq", { serial = true, timeout_ms = 1200000 })
register_test("pirate_pq", { serial = true, timeout_ms = 1800000 })
register_test("npc_scripts", { serial = true, timeout_ms = 1800000 })
register_test("portal_scripts", { serial = true, timeout_ms = 1800000 })
register_test("quest_scripts", { serial = true, timeout_ms = 1800000 })
register_test("npc_explore", { serial = true, explicit = true, timeout_ms = 14400000 })
