register_test("login_smoke")
register_test("npc_dialog")
register_test("channel_transfer")
register_test("combat_smoke")
register_test("reactor_smoke")
register_test("portal_subway", { serial = true })
register_test("kerning_pq", { serial = true, timeout_ms = 600000 })
register_test("carnival_1v1", { serial = true, timeout_ms = 600000 })
register_test("ludibrium_pq", { serial = true, timeout_ms = 1200000 })
register_test("orbis_pq", { serial = true, timeout_ms = 1800000 })
register_test("henesys_pq", { serial = true, timeout_ms = 1200000 })
register_test("pirate_pq", { serial = true, timeout_ms = 1800000 })
register_test("zakum_pq", { serial = true, timeout_ms = 1200000 })
register_test("horntail_pq", { serial = true, timeout_ms = 2400000 })
register_test("magatia_pq", { serial = true, timeout_ms = 1800000 })
register_test("ellin_pq", { serial = true, timeout_ms = 1200000 })
register_test("expedition_boss", { serial = true, timeout_ms = 900000 })
register_test("fourth_job_instance", { serial = true, timeout_ms = 600000 })
register_test("quest_instance", { serial = true, timeout_ms = 1200000 })
register_test("papulatus", { serial = true, timeout_ms = 600000 })
register_test("boss_entry", { serial = true, timeout_ms = 600000 })
register_test("field_boss", { serial = true, timeout_ms = 600000 })
register_test("archer_snipe", { serial = true, timeout_ms = 600000 })
register_test("karta_cave", { serial = true, timeout_ms = 600000 })
register_test("element_thanatos", { serial = true, timeout_ms = 600000 })
register_test("doll_house", { serial = true, timeout_ms = 600000 })
register_test("tame_pig", { serial = true, timeout_ms = 600000 })
register_test("protect_delli", { serial = true, timeout_ms = 600000 })
register_test("air_strike", { serial = true, timeout_ms = 600000 })
register_test("third_job_trial", { serial = true, timeout_ms = 600000 })
register_test("kyrin_test", { serial = true, timeout_ms = 600000 })
register_test("kyrin_training", { serial = true, timeout_ms = 600000 })
register_test("guild_quest", { serial = true, timeout_ms = 900000 })
register_test("npc_scripts", { serial = true, timeout_ms = 1800000 })
register_test("portal_scripts", { serial = true, timeout_ms = 1800000 })
register_test("quest_scripts", { serial = true, timeout_ms = 1800000 })
register_test("npc_explore", { serial = true, explicit = true, timeout_ms = 14400000 })
