// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: fminternal/internal_service.proto

package fminternalpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Internal_Ping_FullMethodName                = "/fm.internal.Internal/Ping"
	Internal_GetServerCatalog_FullMethodName    = "/fm.internal.Internal/GetServerCatalog"
	Internal_EnterGame_FullMethodName           = "/fm.internal.Internal/EnterGame"
	Internal_BeginGameTransition_FullMethodName = "/fm.internal.Internal/BeginGameTransition"
	Internal_SaveCharacter_FullMethodName       = "/fm.internal.Internal/SaveCharacter"
	Internal_SaveCharacters_FullMethodName      = "/fm.internal.Internal/SaveCharacters"
	Internal_LoginAccount_FullMethodName        = "/fm.internal.Internal/LoginAccount"
	Internal_GetCharacterList_FullMethodName    = "/fm.internal.Internal/GetCharacterList"
	Internal_CheckCharacterName_FullMethodName  = "/fm.internal.Internal/CheckCharacterName"
	Internal_CreateCharacter_FullMethodName     = "/fm.internal.Internal/CreateCharacter"
	Internal_DeleteCharacter_FullMethodName     = "/fm.internal.Internal/DeleteCharacter"
	Internal_RefreshSession_FullMethodName      = "/fm.internal.Internal/RefreshSession"
	Internal_LogoutSession_FullMethodName       = "/fm.internal.Internal/LogoutSession"
)

// InternalClient is the client API for Internal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InternalClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error)
	GetServerCatalog(ctx context.Context, in *GetServerCatalogRequest, opts ...grpc.CallOption) (*GetServerCatalogReply, error)
	EnterGame(ctx context.Context, in *EnterGameRequest, opts ...grpc.CallOption) (*EnterGameReply, error)
	BeginGameTransition(ctx context.Context, in *BeginGameTransitionRequest, opts ...grpc.CallOption) (*BeginGameTransitionReply, error)
	SaveCharacter(ctx context.Context, in *SaveCharacterRequest, opts ...grpc.CallOption) (*SaveCharacterReply, error)
	SaveCharacters(ctx context.Context, in *SaveCharactersRequest, opts ...grpc.CallOption) (*SaveCharactersReply, error)
	LoginAccount(ctx context.Context, in *LoginAccountRequest, opts ...grpc.CallOption) (*LoginAccountReply, error)
	GetCharacterList(ctx context.Context, in *GetCharacterListRequest, opts ...grpc.CallOption) (*GetCharacterListReply, error)
	CheckCharacterName(ctx context.Context, in *CheckCharacterNameRequest, opts ...grpc.CallOption) (*CheckCharacterNameReply, error)
	CreateCharacter(ctx context.Context, in *CreateCharacterRequest, opts ...grpc.CallOption) (*CreateCharacterReply, error)
	DeleteCharacter(ctx context.Context, in *DeleteCharacterRequest, opts ...grpc.CallOption) (*DeleteCharacterReply, error)
	RefreshSession(ctx context.Context, in *RefreshSessionRequest, opts ...grpc.CallOption) (*RefreshSessionReply, error)
	LogoutSession(ctx context.Context, in *LogoutSessionRequest, opts ...grpc.CallOption) (*LogoutSessionReply, error)
}

type internalClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalClient(cc grpc.ClientConnInterface) InternalClient {
	return &internalClient{cc}
}

func (c *internalClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingReply)
	err := c.cc.Invoke(ctx, Internal_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalClient) GetServerCatalog(ctx context.Context, in *GetServerCatalogRequest, opts ...grpc.CallOption) (*GetServerCatalogReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerCatalogReply)
	err := c.cc.Invoke(ctx, Internal_GetServerCatalog_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalClient) EnterGame(ctx context.Context, in *EnterGameRequest, opts ...grpc.CallOption) (*EnterGameReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnterGameReply)
	err := c.cc.Invoke(ctx, Internal_EnterGame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalClient) BeginGameTransition(ctx context.Context, in *BeginGameTransitionRequest, opts ...grpc.CallOption) (*BeginGameTransitionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginGameTransitionReply)
	err := c.cc.Invoke(ctx, Internal_BeginGameTransition_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalClient) SaveCharacter(ctx context.Context, in *SaveCharacterRequest, opts ...grpc.CallOption) (*SaveCharacterReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveCharacterReply)
	err := c.cc.Invoke(ctx, Internal_SaveCharacter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalClient) SaveCharacters(ctx context.Context, in *SaveCharactersRequest, opts ...grpc.CallOption) (*SaveCharactersReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveCharactersReply)
	err := c.cc.Invoke(ctx, Internal_SaveCharacters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalClient) LoginAccount(ctx context.Context, in *LoginAccountRequest, opts ...grpc.CallOption) (*LoginAccountReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LoginAccountReply)
	err := c.cc.Invoke(ctx, Internal_LoginAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalClient) GetCharacterList(ctx context.Context, in *GetCharacterListRequest, opts ...grpc.CallOption) (*GetCharacterListReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCharacterListReply)
	err := c.cc.Invoke(ctx, Internal_GetCharacterList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalClient) CheckCharacterName(ctx context.Context, in *CheckCharacterNameRequest, opts ...grpc.CallOption) (*CheckCharacterNameReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckCharacterNameReply)
	err := c.cc.Invoke(ctx, Internal_CheckCharacterName_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalClient) CreateCharacter(ctx context.Context, in *CreateCharacterRequest, opts ...grpc.CallOption) (*CreateCharacterReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCharacterReply)
	err := c.cc.Invoke(ctx, Internal_CreateCharacter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalClient) DeleteCharacter(ctx context.Context, in *DeleteCharacterRequest, opts ...grpc.CallOption) (*DeleteCharacterReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCharacterReply)
	err := c.cc.Invoke(ctx, Internal_DeleteCharacter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalClient) RefreshSession(ctx context.Context, in *RefreshSessionRequest, opts ...grpc.CallOption) (*RefreshSessionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshSessionReply)
	err := c.cc.Invoke(ctx, Internal_RefreshSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *internalClient) LogoutSession(ctx context.Context, in *LogoutSessionRequest, opts ...grpc.CallOption) (*LogoutSessionReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LogoutSessionReply)
	err := c.cc.Invoke(ctx, Internal_LogoutSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalServer is the server API for Internal service.
// All implementations must embed UnimplementedInternalServer
// for forward compatibility.
type InternalServer interface {
	Ping(context.Context, *PingRequest) (*PingReply, error)
	GetServerCatalog(context.Context, *GetServerCatalogRequest) (*GetServerCatalogReply, error)
	EnterGame(context.Context, *EnterGameRequest) (*EnterGameReply, error)
	BeginGameTransition(context.Context, *BeginGameTransitionRequest) (*BeginGameTransitionReply, error)
	SaveCharacter(context.Context, *SaveCharacterRequest) (*SaveCharacterReply, error)
	SaveCharacters(context.Context, *SaveCharactersRequest) (*SaveCharactersReply, error)
	LoginAccount(context.Context, *LoginAccountRequest) (*LoginAccountReply, error)
	GetCharacterList(context.Context, *GetCharacterListRequest) (*GetCharacterListReply, error)
	CheckCharacterName(context.Context, *CheckCharacterNameRequest) (*CheckCharacterNameReply, error)
	CreateCharacter(context.Context, *CreateCharacterRequest) (*CreateCharacterReply, error)
	DeleteCharacter(context.Context, *DeleteCharacterRequest) (*DeleteCharacterReply, error)
	RefreshSession(context.Context, *RefreshSessionRequest) (*RefreshSessionReply, error)
	LogoutSession(context.Context, *LogoutSessionRequest) (*LogoutSessionReply, error)
	mustEmbedUnimplementedInternalServer()
}

// UnimplementedInternalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalServer struct{}

func (UnimplementedInternalServer) Ping(context.Context, *PingRequest) (*PingReply, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedInternalServer) GetServerCatalog(context.Context, *GetServerCatalogRequest) (*GetServerCatalogReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerCatalog not implemented")
}
func (UnimplementedInternalServer) EnterGame(context.Context, *EnterGameRequest) (*EnterGameReply, error) {
	return nil, status.Error(codes.Unimplemented, "method EnterGame not implemented")
}
func (UnimplementedInternalServer) BeginGameTransition(context.Context, *BeginGameTransitionRequest) (*BeginGameTransitionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginGameTransition not implemented")
}
func (UnimplementedInternalServer) SaveCharacter(context.Context, *SaveCharacterRequest) (*SaveCharacterReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveCharacter not implemented")
}
func (UnimplementedInternalServer) SaveCharacters(context.Context, *SaveCharactersRequest) (*SaveCharactersReply, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveCharacters not implemented")
}
func (UnimplementedInternalServer) LoginAccount(context.Context, *LoginAccountRequest) (*LoginAccountReply, error) {
	return nil, status.Error(codes.Unimplemented, "method LoginAccount not implemented")
}
func (UnimplementedInternalServer) GetCharacterList(context.Context, *GetCharacterListRequest) (*GetCharacterListReply, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCharacterList not implemented")
}
func (UnimplementedInternalServer) CheckCharacterName(context.Context, *CheckCharacterNameRequest) (*CheckCharacterNameReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckCharacterName not implemented")
}
func (UnimplementedInternalServer) CreateCharacter(context.Context, *CreateCharacterRequest) (*CreateCharacterReply, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCharacter not implemented")
}
func (UnimplementedInternalServer) DeleteCharacter(context.Context, *DeleteCharacterRequest) (*DeleteCharacterReply, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCharacter not implemented")
}
func (UnimplementedInternalServer) RefreshSession(context.Context, *RefreshSessionRequest) (*RefreshSessionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshSession not implemented")
}
func (UnimplementedInternalServer) LogoutSession(context.Context, *LogoutSessionRequest) (*LogoutSessionReply, error) {
	return nil, status.Error(codes.Unimplemented, "method LogoutSession not implemented")
}
func (UnimplementedInternalServer) mustEmbedUnimplementedInternalServer() {}
func (UnimplementedInternalServer) testEmbeddedByValue()                  {}

// UnsafeInternalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalServer will
// result in compilation errors.
type UnsafeInternalServer interface {
	mustEmbedUnimplementedInternalServer()
}

func RegisterInternalServer(s grpc.ServiceRegistrar, srv InternalServer) {
	// If the following call panics, it indicates UnimplementedInternalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Internal_ServiceDesc, srv)
}

func _Internal_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Internal_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internal_GetServerCatalog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerCatalogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).GetServerCatalog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Internal_GetServerCatalog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).GetServerCatalog(ctx, req.(*GetServerCatalogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internal_EnterGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnterGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).EnterGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Internal_EnterGame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).EnterGame(ctx, req.(*EnterGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internal_BeginGameTransition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginGameTransitionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).BeginGameTransition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Internal_BeginGameTransition_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).BeginGameTransition(ctx, req.(*BeginGameTransitionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internal_SaveCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).SaveCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Internal_SaveCharacter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).SaveCharacter(ctx, req.(*SaveCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internal_SaveCharacters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveCharactersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).SaveCharacters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Internal_SaveCharacters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).SaveCharacters(ctx, req.(*SaveCharactersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internal_LoginAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).LoginAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Internal_LoginAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).LoginAccount(ctx, req.(*LoginAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internal_GetCharacterList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCharacterListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).GetCharacterList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Internal_GetCharacterList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).GetCharacterList(ctx, req.(*GetCharacterListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internal_CheckCharacterName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckCharacterNameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).CheckCharacterName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Internal_CheckCharacterName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).CheckCharacterName(ctx, req.(*CheckCharacterNameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internal_CreateCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).CreateCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Internal_CreateCharacter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).CreateCharacter(ctx, req.(*CreateCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internal_DeleteCharacter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCharacterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).DeleteCharacter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Internal_DeleteCharacter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).DeleteCharacter(ctx, req.(*DeleteCharacterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internal_RefreshSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).RefreshSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Internal_RefreshSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).RefreshSession(ctx, req.(*RefreshSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Internal_LogoutSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogoutSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalServer).LogoutSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Internal_LogoutSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalServer).LogoutSession(ctx, req.(*LogoutSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Internal_ServiceDesc is the grpc.ServiceDesc for Internal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Internal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fm.internal.Internal",
	HandlerType: (*InternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Internal_Ping_Handler,
		},
		{
			MethodName: "GetServerCatalog",
			Handler:    _Internal_GetServerCatalog_Handler,
		},
		{
			MethodName: "EnterGame",
			Handler:    _Internal_EnterGame_Handler,
		},
		{
			MethodName: "BeginGameTransition",
			Handler:    _Internal_BeginGameTransition_Handler,
		},
		{
			MethodName: "SaveCharacter",
			Handler:    _Internal_SaveCharacter_Handler,
		},
		{
			MethodName: "SaveCharacters",
			Handler:    _Internal_SaveCharacters_Handler,
		},
		{
			MethodName: "LoginAccount",
			Handler:    _Internal_LoginAccount_Handler,
		},
		{
			MethodName: "GetCharacterList",
			Handler:    _Internal_GetCharacterList_Handler,
		},
		{
			MethodName: "CheckCharacterName",
			Handler:    _Internal_CheckCharacterName_Handler,
		},
		{
			MethodName: "CreateCharacter",
			Handler:    _Internal_CreateCharacter_Handler,
		},
		{
			MethodName: "DeleteCharacter",
			Handler:    _Internal_DeleteCharacter_Handler,
		},
		{
			MethodName: "RefreshSession",
			Handler:    _Internal_RefreshSession_Handler,
		},
		{
			MethodName: "LogoutSession",
			Handler:    _Internal_LogoutSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fminternal/internal_service.proto",
}
