// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: fminternal/ping.proto

package fminternalpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_fminternal_ping_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fminternal_ping_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_fminternal_ping_proto_rawDescGZIP(), []int{0}
}

type PingReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingReply) Reset() {
	*x = PingReply{}
	mi := &file_fminternal_ping_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingReply) ProtoMessage() {}

func (x *PingReply) ProtoReflect() protoreflect.Message {
	mi := &file_fminternal_ping_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingReply.ProtoReflect.Descriptor instead.
func (*PingReply) Descriptor() ([]byte, []int) {
	return file_fminternal_ping_proto_rawDescGZIP(), []int{1}
}

func (x *PingReply) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_fminternal_ping_proto protoreflect.FileDescriptor

const file_fminternal_ping_proto_rawDesc = "" +
	"\n" +
	"\x15fminternal/ping.proto\x12\vfm.internal\"\r\n" +
	"\vPingRequest\"%\n" +
	"\tPingReply\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2D\n" +
	"\bInternal\x128\n" +
	"\x04Ping\x12\x18.fm.internal.PingRequest\x1a\x16.fm.internal.PingReplyBHZFgithub.com/boyism80/fm/protocol/protobuf/gengo/fminternal;fminternalpbb\x06proto3"

var (
	file_fminternal_ping_proto_rawDescOnce sync.Once
	file_fminternal_ping_proto_rawDescData []byte
)

func file_fminternal_ping_proto_rawDescGZIP() []byte {
	file_fminternal_ping_proto_rawDescOnce.Do(func() {
		file_fminternal_ping_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fminternal_ping_proto_rawDesc), len(file_fminternal_ping_proto_rawDesc)))
	})
	return file_fminternal_ping_proto_rawDescData
}

var file_fminternal_ping_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fminternal_ping_proto_goTypes = []any{
	(*PingRequest)(nil), // 0: fm.internal.PingRequest
	(*PingReply)(nil),   // 1: fm.internal.PingReply
}
var file_fminternal_ping_proto_depIdxs = []int32{
	0, // 0: fm.internal.Internal.Ping:input_type -> fm.internal.PingRequest
	1, // 1: fm.internal.Internal.Ping:output_type -> fm.internal.PingReply
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fminternal_ping_proto_init() }
func file_fminternal_ping_proto_init() {
	if File_fminternal_ping_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fminternal_ping_proto_rawDesc), len(file_fminternal_ping_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fminternal_ping_proto_goTypes,
		DependencyIndexes: file_fminternal_ping_proto_depIdxs,
		MessageInfos:      file_fminternal_ping_proto_msgTypes,
	}.Build()
	File_fminternal_ping_proto = out.File
	file_fminternal_ping_proto_goTypes = nil
	file_fminternal_ping_proto_depIdxs = nil
}
