package entity

import (
	"time"

	"github.com/asynkron/protoactor-go/actor"
	"github.com/boyism80/fm/core/async"
	pconst "github.com/boyism80/fm/protocol/constant"
	"github.com/boyism80/fm/protocol/dto"
	internal "github.com/boyism80/fm/protocol/protobuf/gengo/fminternal"
	"github.com/boyism80/fm/protocol/response"
	"github.com/boyism80/fm/services/game/constant"
	"github.com/boyism80/fm/services/game/wz"
	"github.com/boyism80/fm/types"
)

type CharacterListener interface {
	OnDialog(ch *Character, npc uint32, message string, prev bool, next bool)
	OnDialogYesNo(ch *Character, npc uint32, message string, prev bool, next bool)
	OnDialogAccept(ch *Character, npc uint32, message string, enableEscape bool)
	OnDialogList(ch *Character, npc uint32, message string, selections []string)
	OnDialogInput(ch *Character, npc uint32, message string)
	OnDialogStyle(ch *Character, npc uint32, message string, styles []uint32)
	OnOpenNpcShop(ch *Character, shopID uint32, shop *wz.Shop)
	LoadStorageAsync(ctx actor.Context, ch *Character) *async.Promise[*internal.LoadStorageReply]
	OnOpenStorage(ch *Character, npcID uint32)
	OnStorageTabChanged(ch *Character, result pconst.StorageResult, invType constant.InventoryType)
	OnStorageArranged(ch *Character)
	OnStorageMesoChanged(ch *Character)
	OnStorageError(ch *Character, result pconst.StorageResult)
	LoadParcelsAsync(ctx actor.Context, ch *Character) *async.Promise[*internal.LoadParcelsReply]
	SendParcelAsync(ctx actor.Context, ch *Character, recipient string, parcel *internal.Parcel, oneOfAKind bool, sender *internal.CharacterSaveEntry) *async.Promise[*internal.SendParcelReply]
	ClaimParcelAsync(ctx actor.Context, ch *Character, parcelID uint32) *async.Promise[*internal.ClaimParcelReply]
	DeleteParcelAsync(ctx actor.Context, ch *Character, parcelID uint32) *async.Promise[*internal.DeleteParcelReply]
	CheckParcelArrivalsAsync(ctx actor.Context, ch *Character) *async.Promise[*internal.CheckParcelArrivalsReply]
	AddCashAsync(ctx actor.Context, ch *Character, nxCash int32, maplePoint int32) *async.Promise[*internal.AddCashReply]
	CreateCashCouponsAsync(ctx actor.Context, ch *Character, kind internal.CashCouponKind, value uint32, count uint32) *async.Promise[*internal.CreateCashCouponsReply]
	CreateMarriageAsync(ctx actor.Context, groom *Character, bride *Character, ringItemID uint32) *async.Promise[*internal.MarriageReply]
	LoadMarriageAsync(ctx actor.Context, ch *Character) *async.Promise[*internal.MarriageReply]
	GetMarriageAsync(ctx actor.Context, ch *Character, marriageID uint32) *async.Promise[*internal.MarriageReply]
	BreakEngagementAsync(ctx actor.Context, ch *Character, marriageID uint32) *async.Promise[*internal.MarriageReply]
	ReserveWeddingAsync(ctx actor.Context, ch *Character, marriageID uint32, ticketItemID uint32) *async.Promise[*internal.MarriageReply]
	SetWeddingWishlistAsync(ctx actor.Context, ch *Character, marriageID uint32, wishes []string) *async.Promise[*internal.MarriageReply]
	InviteWeddingGuestAsync(ctx actor.Context, ch *Character, marriageID uint32, guestName string) *async.Promise[*internal.InviteWeddingGuestReply]
	RequestDivorceAsync(ctx actor.Context, ch *Character, marriageID uint32) *async.Promise[*internal.MarriageReply]
	CancelDivorceAsync(ctx actor.Context, ch *Character, marriageID uint32) *async.Promise[*internal.MarriageReply]
	GiveWeddingGiftAsync(ctx actor.Context, ch *Character, receiverID uint32, gift *internal.WeddingGift, sender *internal.CharacterSaveEntry) *async.Promise[*internal.GiveWeddingGiftReply]
	LoadWeddingGiftsAsync(ctx actor.Context, ch *Character) *async.Promise[*internal.LoadWeddingGiftsReply]
	ClaimWeddingGiftAsync(ctx actor.Context, ch *Character, giftID uint32) *async.Promise[*internal.ClaimWeddingGiftReply]
	NotifySpouseMapAsync(ctx actor.Context, ch *Character, spouseID uint32, mapID uint32, reply bool) *async.Promise[*internal.NotifySpouseMapReply]
	OnEngageRequest(ch *Character, name string, characterID uint32)
	OnWeddingWishlistInput(ch *Character)
	OnEngageResult(ch *Character, result pconst.EngageResult)
	OnWeddingInvitation(ch *Character, groomName string, brideName string, weddingType uint16)
	OnWeddingGift(ch *Character, mode pconst.WeddingGiftMode, wishes []string, tabs map[constant.InventoryType][]Item)
	OnSpouseMap(ch *Character, mapID uint32, spouseID uint32)
	OnOpenDuey(ch *Character, fromArrival bool)
	OnDueyResult(ch *Character, result pconst.DueyResult)
	OnDueyRemoved(ch *Character, parcelID uint32, reason uint8)
	OnDueyArrival(ch *Character, sender string, quick bool, count int)
	FindEntrustedShopAsync(ctx actor.Context, ch *Character) *async.Promise[*internal.FindEntrustedShopReply]
	OpenShopAsync(ctx actor.Context, ch *Character, shop *internal.Shop) *async.Promise[*internal.OpenShopReply]
	ClaimStoreBankAsync(ctx actor.Context, ch *Character) *async.Promise[*internal.ClaimStoreBankReply]
	SearchShopsAsync(ctx actor.Context, ch *Character, itemID uint32, highFirst bool) *async.Promise[*internal.SearchShopsReply]
	FindPopularShopSearchesAsync(ctx actor.Context, ch *Character) *async.Promise[*internal.FindPopularShopSearchesReply]
	OnEntrustedShopCheck(ch *Character, result pconst.EntrustedShopCheck, mapID uint32, channel uint8)
	OnEntrustedShopRemoteVisit(ch *Character, sn uint32)
	OnShopScannerResult(ch *Character, itemID uint32, entries []*internal.ShopSearchEntry)
	OnShopScannerPopular(ch *Character, itemIDs []uint32)
	OnPersonalShopEntered(ch *Character, ps *PersonalShop)
	OnPersonalShopItems(ch *Character, ps *PersonalShop)
	OnMiniRoomSold(ch *Character, index uint8, bundles uint16, buyer string)
	OnMiniRoomItemRemoved(ch *Character, count uint8, index uint16)
	OnMiniRoomBalloon(ch *Character, balloon *response.MiniRoomBalloon)
	OnMiniRoomEntered(ch *Character, slot uint8, view EntrustedShopView, firstTime bool)
	OnMiniRoomEnterFailed(ch *Character, code pconst.MiniRoomEnterError)
	OnMiniRoomVisited(ch *Character, slot uint8, visitor *Character)
	OnMiniRoomChat(ch *Character, slot uint8, text string)
	OnMiniRoomLeft(ch *Character, slot uint8, reason pconst.MiniRoomLeaveReason)
	OnMiniRoomItems(ch *Character, view EntrustedShopView)
	OnMiniRoomBuyFailed(ch *Character, result pconst.MiniRoomBuyResult)
	OnMiniRoomArranged(ch *Character, view EntrustedShopView)
	OnMiniRoomClosed(ch *Character, result pconst.MiniRoomCloseResult)
	OnMiniRoomMesoWithdrawn(ch *Character)
	OnOpenStoreBank(ch *Character, npcID uint32)
	OnStoreBankFee(ch *Character, days uint32, fee int32)
	OnStoreBankLocation(ch *Character, npcID uint32, mapID uint32, channel uint8)
	OnStoreBankResult(ch *Character, result pconst.StoreBankResult)
	OnGuildBulletinThreadList(ch *Character, threads []*internal.GuildBulletinBoardThreadEntry, start int, totalCount int, notice *internal.GuildBulletinBoardThreadEntry)
	OnGuildBulletinThread(ch *Character, detail *internal.GuildBulletinBoardThreadDetail)
	OnShipState(ch *Character, state uint16)
	OnShipBalrog(ch *Character)
	OnSitOnChair(ch *Character, itemID uint32)
	OnSitOnMapSeat(ch *Character, seatID int16)
	OnStandUp(ch *Character)
	OnBuddyCapacity(ch *Character, capacity uint8)
	OnChat(ch *Character, message string, highlight bool, dontRecordHistory bool)
	OnMesoChanged(ch *Character, meso int32)
	OnMessage(ch *Character, messageType constant.ServerMessageType, message string)
	OnNotice(ch *Character, messageType constant.ServerMessageType, message string, channel int, ear bool)
	BroadcastNoticeAsync(ctx actor.Context, ch *Character, messageType constant.ServerMessageType, message string, ear bool) *async.Promise[*internal.BroadcastNoticeReply]
	OnKeyMap(ch *Character)
	OnClock(ch *Character, seconds int32)
	OnStopClock(ch *Character)
	OnPartyCreated(ch *Character, partyID uint32)
	OnShowGuildInfo(ch *Character)
	OnShowAllianceInfo(ch *Character)
	OnAllianceUpdateInfo(ch *Character)
	OnBroadcastGuildAppearance(ch *Character)
	OnPartyInvite(ch *Character, partyID uint32, inviterName string, partySearch bool)
	OnGuildInvite(ch *Character, guildID uint32, inviterName string)
	OnAllianceInvite(ch *Character, inviterGuildID uint32, inviterName string, allianceName string)
	OnAllianceCreate(ch *Character, info *dto.AllianceInfo, guilds []*dto.GuildInfo, membershipGuilds []dto.AllianceMembershipChangeGuild)
	OnAllianceDisband(ch *Character, allianceID uint32)
	OnAllianceInfoBroadcast(ch *Character, info *dto.AllianceInfo)
	OnAllianceNoticeChanged(ch *Character, info *dto.AllianceInfo)
	OnAllianceLeaderChanged(ch *Character, allianceID uint32, oldLeaderID uint32, newLeaderID uint32, info *dto.AllianceInfo, guilds []*dto.GuildInfo)
	OnAllianceMemberRankChanged(ch *Character, info *dto.AllianceInfo, guilds []*dto.GuildInfo)
	OnAllianceGuildAdded(ch *Character, info *dto.AllianceInfo, guilds []*dto.GuildInfo, newGuildID uint32, addedGuild *dto.GuildInfo, members []dto.AllianceGuildMemberRank, joining bool, membershipGuild *dto.AllianceMembershipChangeGuild)
	OnAllianceGuildLeft(ch *Character, info *dto.AllianceInfo, removedGuildID uint32, removedGuild *dto.GuildInfo, removedMembers []dto.AllianceGuildMemberRank, expelled bool, leaving bool)
	OnGuildNewMember(ch *Character, guildID uint32, member dto.GuildMemberStatus)
	OnGuildLeaveSelf(ch *Character)
	OnGuildExpelledSelf(ch *Character, guildID uint32)
	OnGuildMemberLeft(ch *Character, guildID uint32, targetID uint32, targetName string, wasExpelled bool)
	OnGuildRankTitleChange(ch *Character, guildID uint32, rankTitles [5]string)
	OnGuildMemberRankChange(ch *Character, guildID uint32, targetID uint32, guildRank uint8)
	OnGuildEmblemChange(ch *Character, guildID uint32, logoBG uint16, logoBGColor uint8, logo uint16, logoColor uint8)
	OnGuildNoticeChange(ch *Character, guildID uint32, notice string)
	OnGuildCapacityChange(ch *Character, guildID uint32, capacity uint8)
	OnGuildGPChange(ch *Character, guildID uint32, gp uint32, level uint32, amount int32)
	OnGuildRanking(ch *Character, npcID uint32, entries []dto.GuildRankingEntry)
	OnGuildMemberOnlineChange(ch *Character, guildID uint32, subjectCharacterID uint32, online bool)
	OnGuildMemberFieldsChange(ch *Character, guildID uint32, subjectCharacterID uint32, level uint32, classID uint32)
	OnAllianceMemberOnlineChange(ch *Character, allianceID uint32, guildID uint32, subjectCharacterID uint32, online bool)
	OnAllianceMemberFieldsChange(ch *Character, allianceID uint32, guildID uint32, subjectCharacterID uint32, level uint32, classID uint32)
	OnGuildDisbandSelf(ch *Character, guildID uint32)
	OnMultiChat(ch *Character, mode pconst.MultiChatMode, senderName string, message string)
	OnPartyStatusMessage(ch *Character, code pconst.PartyStatusCode, name string)
	OnPartyUpdateJoin(ch *Character, forChannel int32, partyID uint32, joinName string, leaderID uint32, members []response.PartyMemberStatus)
	OnPartyUpdateExpel(ch *Character, forChannel int32, partyID uint32, targetID uint32, targetName string, leaderID uint32, members []response.PartyMemberStatus)
	OnPartyUpdateLeave(ch *Character, forChannel int32, partyID uint32, targetID uint32, targetName string, leaderID uint32, members []response.PartyMemberStatus)
	OnPartyUpdateDisband(ch *Character, partyID uint32, leaderID uint32)
	OnPartyUpdateLeaderChange(ch *Character, newLeaderID uint32, byDisconnect bool)
	OnPartyUpdateLogOnOff(ch *Character, forChannel int32, partyID uint32, leaderID uint32, members []response.PartyMemberStatus)
	OnPartyUpdateSilent(ch *Character, forChannel int32, partyID uint32, leaderID uint32, members []response.PartyMemberStatus)
	OnBuddyStatusMessage(ch *Character, code pconst.BuddyStatusCode)
	OnBuddyChannelUpdate(ch *Character, buddyCharacterID uint32, channel int32)
	OnBuddyListUpdate(ch *Character, action pconst.BuddyListSyncAction, entries []response.BuddyEntry)
	OnBuddyAddRequest(ch *Character, fromCharacterID uint32, fromName string)
	OnGuildMessage(ch *Character, code pconst.GuildResponseCode)
	OnExpGain(ch *Character, exp uint32)
	OnControlMoveMob(ch *Character, mob *Mob, moveId uint16, enabledSkill bool, mp uint16, skillId uint32, skillLevel uint8)
	OnShowMobHp(ch *Character, mob *Mob, percentage uint8)
	OnDojoEnergy(ch *Character, energy int)
	OnUnlockAction(ch *Character)
	OnInspect(ch *Character, profile *response.CharacterProfile)
	OnMonsterBookCardRegistered(ch *Character, cardID uint32, count uint32)
	OnMonsterBookCardFull(ch *Character)
	OnMonsterBookCover(ch *Character, cardID uint32)
	OnTeleportStones(ch *Character, vip bool)
	OnTeleportStoneFailed(ch *Character, vip bool, result pconst.TeleportStoneResult)
	OnScriptError(ch *Character, script string, err error)
	OnQuestStarted(ch *Character, qp *Quest, npcID uint32)
	OnQuestCompleted(ch *Character, qp *Quest, npcID uint32, nextQuestID uint32)
	OnQuestForfeited(ch *Character, qp *Quest)
	OnQuestProgress(ch *Character, qp *Quest)
	OnQuestRecordExChanged(ch *Character, qp *Quest)
	OnShowQuestCompletion(ch *Character, questID uint32)
	OnPlaySound(ch *Character, sound string, broadcast bool)
	OnPlayPortalSound(ch *Character)
	OnItemGainFailed(ch *Character, mode constant.ItemGainFailedType)
	OnInventorySlotUpdated(ch *Character, inventoryType constant.InventoryType, slot int16, item Item)
	OnInventorySlotAdded(ch *Character, inventoryType constant.InventoryType, slot int16, item Item)
	OnShowItemGain(ch *Character, itemId uint32, count uint32, mode constant.ShowItemGainType)
	OnShowMesoGain(ch *Character, count int32, mode constant.ShowMesoGainType)
	OnUpdateStats(ch *Character, stats map[constant.Stat]int32, unlock bool)
	OnMobMoved(ch *Character, mob *Mob, isAggroed bool, centerSplit int8, skill1 uint8, skill2 uint8, skill3 uint8, skill4 uint8, startPoint types.Vector2[int16], movements []dto.MoveFragment)
	OnPlayerMove(ch *Character, startPoint types.Vector2[int16], fragments []dto.MoveFragment)
	OnFieldRelocate(ch *Character, spawnPoint uint8)
	OnAttack(ch *Character, attackPayload dto.AttackPayload, skillLevel uint8)
	OnRangedAttack(ch *Character, attackPayload dto.AttackPayload, skillLevel uint8)
	OnMagicAttack(ch *Character, attackPayload dto.AttackPayload, skillLevel uint8)
	OnEndSortInventory(ch *Character, inventoryType constant.InventoryType)
	OnSwapInventorySlot(ch *Character, inventoryType constant.InventoryType, source int16, dest int16, equipmentAction int8)
	OnRemoveInventorySlot(ch *Character, inventoryType constant.InventoryType, slot int16)
	OnFullMergeInventorySlot(ch *Character, inventoryType constant.InventoryType, source int16, dest int16, count uint16)
	OnPartialMergeInventorySlot(ch *Character, inventoryType constant.InventoryType, source int16, dest int16, sourceCount uint16, destCount uint16)
	OnUpdateCharacterLook(ch *Character)
	OnNpcAction(ch *Character, bytes []byte)
	OnClassChange(ch *Character, oldClass uint16, newClass uint16)
	OnPartyMemberFieldsChanged(ch *Character)
	OnPartyMemberHPChanged(ch *Character, recipient *Character)
	OnBuffAdded(ch *Character, buffID int32, remainingDuration time.Duration, values map[constant.BuffFlag]int32)
	OnBuffRemoved(ch *Character, flags []constant.BuffFlag)
	OnDebuffAdded(ch *Character, debuff constant.DebuffFlag, x int16, skillID uint16, skillLevel uint16, durationMs int32)
	OnDebuffRemoved(ch *Character, flags []constant.DebuffFlag)
	OnSkillCooldown(ch *Character, skillID uint32, remainingSec uint16)
	OnUpdateSkill(ch *Character, skillID uint32, level int32, masterLevel int32)
	OnHiddenChanged(ch *Character, hidden bool)
	OnShowSelfSkillEffect(ch *Character, effectType pconst.SkillEffectType, skillID uint32, skillLevel uint8, additional *uint8)
	OnShowSkillEffect(ch *Character, effectType pconst.SkillEffectType, skillID uint32, skillLevel uint8, additional *uint8)
	OnShowSelfEffect(ch *Character, effectType response.EffectType)
	OnShowEffect(ch *Character, effectType response.EffectType)
	OnShowSelfDragonBloodEffect(ch *Character, skillID uint32, skillLevel uint8)
	OnShowDragonBloodEffect(ch *Character, skillID uint32, skillLevel uint8)
	OnShowSelfHPHealedEffect(ch *Character, amount int32)
	OnShowHPHealedEffect(ch *Character, amount int32)
	OnShowSelfRewardItemAnimation(ch *Character, itemID uint32, effect string)
	OnShowRewardItemAnimation(ch *Character, itemID uint32, effect string)
	OnShowSelfItemMakerSuccessEffect(ch *Character)
	OnShowItemMakerSuccessEffect(ch *Character)
	OnShowSelfCraftingEffect(ch *Character, effect string, time int32, mode int32)
	OnShowCraftingEffect(ch *Character, effect string, time int32, mode int32)
	OnShowSelfDiceEffect(ch *Character, effectID int32, skillID uint32, skillLevel uint8)
	OnShowDiceEffect(ch *Character, effectID int32, skillID uint32, skillLevel uint8)
	OnShowScrollEffect(ch *Character, success bool, destroyedByCurse bool)
	OnScrolledItem(ch *Character, scrollInventoryType constant.InventoryType, scrollSlot int16, scrollCount uint16, upgradedSlot int16, destroyed bool, potential bool, upgradedItem Item)
	OnPetSpawn(ch *Character)
	OnPetRemove(ch *Character, reason constant.PetRemoveReason)
	OnPetMove(ch *Character, startPoint types.Vector2[int16], movements []dto.MoveFragment)
	OnPetChat(ch *Character, typ uint8, action uint8, text string)
	OnPetCommand(ch *Character, index uint8, success bool)
	OnPetFood(ch *Character, success bool)
	OnPetUpdated(ch *Character, pet *Pet)
	OnPetLevelUp(ch *Character)
	OnPetExceptions(ch *Character)
	OnPetNameChanged(ch *Character)
	OnPetSkillChanged(ch *Character, pet *Pet, skill constant.PetSkill, add bool)
	OnSummonSpawn(ch *Character, summon *Summon)
	OnSummonRemove(ch *Character, summon *Summon, animated bool)
	OnSummonMove(ch *Character, summon *Summon, startPoint types.Vector2[int16], movements []dto.MoveFragment)
	OnSummonAttack(ch *Character, summon *Summon, animation uint8, targets []SummonAttackTarget)
	OnSummonSkill(ch *Character, summon *Summon, newStance uint8)
	OnSummonDamaged(ch *Character, summon *Summon, unknown uint8, damage uint32, monsterIdFrom uint32)
	OnCarnivalStart(ch *Character, team constant.CarnivalTeam, persAvail, persTotal, friendAvail, friendTotal, enemyAvail, enemyTotal int)
	OnCarnivalObtainedCP(ch *Character, avail, total int)
	OnCarnivalPartyCP(ch *Character, team constant.CarnivalTeam, avail, total int)
	OnCarnivalSummon(ch *Character, tab constant.CarnivalTab, num uint8, name string)
	OnCarnivalDied(ch *Character, team constant.CarnivalTeam, name string, lostCP uint8)
	OnCarnivalResult(ch *Character, winner bool)
	OnConfirmShopTransaction(ch *Character, code uint8)
}

type MobListener interface {
	OnMobBuffApplied(mob *Mob, ent *MobBuff, addedReflections []int32, remaining time.Duration)
	OnMobBuffCancelled(mob *Mob, buff constant.MobBuffFlag)
	OnMobDamaged(mob *Mob, amount int32)
	OnMobAllyDamaged(mob *Mob, amount int32)
	OnShowBossHp(mob *Mob, clear bool)
}
