package entity

import (
	"time"

	pconst "github.com/boyism80/fm/protocol/constant"
	"github.com/boyism80/fm/protocol/dto"
	"github.com/boyism80/fm/protocol/response"
	"github.com/boyism80/fm/services/game/constant"
	"github.com/boyism80/fm/types"
)

type CharacterListener interface {
	OnDialog(ch *Character, npc uint32, message string, prev bool, next bool)
	OnDialogYesNo(ch *Character, npc uint32, message string, prev bool, next bool)
	OnDialogAccept(ch *Character, npc uint32, message string, enableEscape bool)
	OnDialogList(ch *Character, npc uint32, message string, selections []string)
	OnDialogInput(ch *Character, npc uint32, message string)
	OnChat(ch *Character, message string, highlight bool, dontRecordHistory bool)
	OnMesoChanged(ch *Character, meso int32)
	OnMessage(ch *Character, messageType constant.ServerMessageType, message string)
	OnPartyCreated(ch *Character, partyID uint32)
	OnShowGuildInfo(ch *Character)
	OnBroadcastGuildAppearance(ch *Character)
	OnPartyInvite(ch *Character, partyID uint32, inviterName string, partySearch bool)
	OnGuildInvite(ch *Character, guildID uint32, inviterName string)
	OnGuildNewMember(ch *Character, guildID uint32, member dto.GuildMemberStatus)
	OnGuildLeaveSelf(ch *Character)
	OnGuildExpelledSelf(ch *Character, guildID uint32)
	OnGuildMemberLeft(ch *Character, guildID uint32, targetID uint32, targetName string, wasExpelled bool)
	OnGuildRankTitleChange(ch *Character, guildID uint32, rankTitles [5]string)
	OnGuildMemberRankChange(ch *Character, guildID uint32, targetID uint32, guildRank uint8)
	OnGuildEmblemChange(ch *Character, guildID uint32, logoBG uint16, logoBGColor uint8, logo uint16, logoColor uint8)
	OnGuildNoticeChange(ch *Character, guildID uint32, notice string)
	OnGuildMemberOnlineChange(ch *Character, guildID uint32, subjectCharacterID uint32, online bool)
	OnGuildDisbandSelf(ch *Character, guildID uint32)
	OnMultiChat(ch *Character, mode pconst.MultiChatMode, senderName string, message string)
	OnPartyStatusMessage(ch *Character, code pconst.PartyStatusCode, name string)
	OnPartyUpdateJoin(ch *Character, forChannel int32, partyID uint32, joinName string, leaderID uint32, members []response.PartyMemberStatus)
	OnPartyUpdateExpel(ch *Character, forChannel int32, partyID uint32, targetID uint32, targetName string, leaderID uint32, members []response.PartyMemberStatus)
	OnPartyUpdateLeave(ch *Character, forChannel int32, partyID uint32, targetID uint32, targetName string, leaderID uint32, members []response.PartyMemberStatus)
	OnPartyUpdateDisband(ch *Character, partyID uint32, leaderID uint32)
	OnPartyUpdateLeaderChange(ch *Character, newLeaderID uint32, byDisconnect bool)
	OnPartyUpdateLogOnOff(ch *Character, forChannel int32, partyID uint32, leaderID uint32, members []response.PartyMemberStatus)
	OnPartyUpdateSilent(ch *Character, forChannel int32, partyID uint32, leaderID uint32, members []response.PartyMemberStatus)
	OnBuddyStatusMessage(ch *Character, code pconst.BuddyStatusCode)
	OnBuddyChannelUpdate(ch *Character, buddyCharacterID uint32, channel int32)
	OnBuddyListUpdate(ch *Character, action pconst.BuddyListSyncAction, entries []response.BuddyEntry)
	OnBuddyAddRequest(ch *Character, fromCharacterID uint32, fromName string)
	OnGuildMessage(ch *Character, code pconst.GuildResponseCode)
	OnExpGain(ch *Character, exp uint32)
	OnControlMoveMob(ch *Character, mob *Mob, moveId uint16, enabledSkill bool, mp uint16, skillId uint32, skillLevel uint8)
	OnShowMobHp(ch *Character, mob *Mob, percentage uint8)
	OnUnlockAction(ch *Character)
	OnItemGainFailed(ch *Character, mode constant.ItemGainFailedType)
	OnInventorySlotUpdated(ch *Character, inventoryType constant.InventoryType, slot int16, item Item)
	OnInventorySlotAdded(ch *Character, inventoryType constant.InventoryType, slot int16, item Item)
	OnShowItemGain(ch *Character, itemId uint32, count uint32, mode constant.ShowItemGainType)
	OnShowMesoGain(ch *Character, count int32, mode constant.ShowMesoGainType)
	OnUpdateStats(ch *Character, stats map[constant.Stat]int32, unlock bool)
	OnMobMoved(ch *Character, mob *Mob, isAggroed bool, centerSplit int8, skill1 uint8, skill2 uint8, skill3 uint8, skill4 uint8, startPoint types.Vector2[int16], movements []dto.MoveFragment)
	OnPlayerMove(ch *Character, startPoint types.Vector2[int16], fragments []dto.MoveFragment)
	OnAttack(ch *Character, attackPayload dto.AttackPayload, skillLevel uint8)
	OnRangedAttack(ch *Character, attackPayload dto.AttackPayload, skillLevel uint8)
	OnMagicAttack(ch *Character, attackPayload dto.AttackPayload, skillLevel uint8)
	OnEndSortInventory(ch *Character, inventoryType constant.InventoryType)
	OnSwapInventorySlot(ch *Character, inventoryType constant.InventoryType, source int16, dest int16, equipmentAction int8)
	OnRemoveInventorySlot(ch *Character, inventoryType constant.InventoryType, slot int16)
	OnUpdateInventorySlot(ch *Character, inventoryType constant.InventoryType, slot int16, item Item)
	OnFullMergeInventorySlot(ch *Character, inventoryType constant.InventoryType, source int16, dest int16, count uint16)
	OnPartialMergeInventorySlot(ch *Character, inventoryType constant.InventoryType, source int16, dest int16, sourceCount uint16, destCount uint16)
	OnUpdateCharacterLook(ch *Character)
	OnNpcAction(ch *Character, bytes []byte)
	OnClassChange(ch *Character, oldClass uint16, newClass uint16)
	OnPartyMemberFieldsChanged(ch *Character)
	OnPartyMemberHPChanged(ch *Character, recipient *Character)
	OnBuffAdded(ch *Character, buffID int32, remainingDuration time.Duration, values map[constant.BuffFlag]int32)
	OnBuffRemoved(ch *Character, flags []constant.BuffFlag)
	OnDebuffAdded(ch *Character, debuff constant.DebuffFlag, x int16, skillID uint16, skillLevel uint16, durationMs int32)
	OnDebuffRemoved(ch *Character, flags []constant.DebuffFlag)
	OnSkillCooldown(ch *Character, skillID uint32, remainingSec uint16)
	OnUpdateSkill(ch *Character, skillID uint32, level int32, masterLevel int32)
	OnSkillPassiveHook(ch *Character, skillID uint32, hook string)
	OnHiddenChanged(ch *Character, hidden bool)
	OnShowSelfSkillEffect(ch *Character, effectType pconst.SkillEffectType, skillID uint32, skillLevel uint8, additional *uint8)
	OnShowSkillEffect(ch *Character, effectType pconst.SkillEffectType, skillID uint32, skillLevel uint8, additional *uint8)
	OnShowSelfEffect(ch *Character, effectType response.EffectType)
	OnShowEffect(ch *Character, effectType response.EffectType)
	OnShowSelfDragonBloodEffect(ch *Character, skillID uint32, skillLevel uint8)
	OnShowDragonBloodEffect(ch *Character, skillID uint32, skillLevel uint8)
	OnShowSelfHPHealedEffect(ch *Character, amount int32)
	OnShowHPHealedEffect(ch *Character, amount int32)
	OnShowSelfRewardItemAnimation(ch *Character, itemID uint32, effect string)
	OnShowRewardItemAnimation(ch *Character, itemID uint32, effect string)
	OnShowSelfItemMakerSuccessEffect(ch *Character)
	OnShowItemMakerSuccessEffect(ch *Character)
	OnShowSelfCraftingEffect(ch *Character, effect string, time int32, mode int32)
	OnShowCraftingEffect(ch *Character, effect string, time int32, mode int32)
	OnShowSelfDiceEffect(ch *Character, effectID int32, skillID uint32, skillLevel uint8)
	OnShowDiceEffect(ch *Character, effectID int32, skillID uint32, skillLevel uint8)
	OnShowScrollEffect(ch *Character, success bool, destroyedByCurse bool)
	OnScrolledItem(ch *Character, scrollInventoryType constant.InventoryType, scrollSlot int16, scrollCount uint16, upgradedSlot int16, destroyed bool, potential bool, upgradedItem Item)
	OnSummonSpawn(ch *Character, summon *Summon)
	OnSummonRemove(ch *Character, summon *Summon, animated bool)
	OnSummonMove(ch *Character, summon *Summon, startPoint types.Vector2[int16], movements []dto.MoveFragment)
	OnSummonAttack(ch *Character, summon *Summon, animation uint8, targets []SummonAttackTarget)
	OnSummonSkill(ch *Character, summon *Summon, newStance uint8)
	OnSummonDamaged(ch *Character, summon *Summon, unknown uint8, damage uint32, monsterIdFrom uint32)
}

type MobListener interface {
	OnMobBuffApplied(mob *Mob, ent *MobBuff, addedReflections []int32, remaining time.Duration)
	OnMobBuffCancelled(mob *Mob, buff constant.MobBuffFlag)
	OnMobDamaged(mob *Mob, amount int32)
}
