import type { CharacterPersisted } from "../protobuf/generated/fminternal/internal_service";

export function makeCharacterMessage(p: any): CharacterPersisted {
    return {
        characterId: p.characterId >>> 0,
        worldId: p.worldId >>> 0,
        name: p.name ?? "",
        gender: p.gender >>> 0,
        skinColor: p.skinColor >>> 0,
        face: p.face >>> 0,
        hair: p.hair >>> 0,
        level: p.level >>> 0,
        classId: p.classId >>> 0,
        role: (p.role ?? 0) >>> 0,
        str: p.str >>> 0,
        dex: p.dex >>> 0,
        intStat: p.intStat >>> 0,
        luk: p.luk >>> 0,
        hp: p.hp >>> 0,
        maxHp: p.maxHp >>> 0,
        mp: p.mp >>> 0,
        maxMp: p.maxMp >>> 0,
        abilityPoint: p.abilityPoint >>> 0,
        exp: p.exp >>> 0,
        mapId: p.mapId >>> 0,
        spawnPoint: p.spawnPoint >>> 0,
        positionX: p.positionX | 0,
        positionY: p.positionY | 0,
        stance: p.stance >>> 0,
        meso: p.meso | 0,
        skillPoint: p.skillPoint >>> 0,
        accountId: p.accountId >>> 0,
        hidden: Boolean(p.hidden),
    };
}

export function persistedFromMessage(msg: CharacterPersisted) {
    return {
        characterId: msg.characterId >>> 0,
        worldId: msg.worldId >>> 0,
        name: msg.name,
        gender: msg.gender >>> 0,
        skinColor: msg.skinColor >>> 0,
        face: msg.face >>> 0,
        hair: msg.hair >>> 0,
        level: msg.level >>> 0,
        classId: msg.classId >>> 0,
        role: msg.role >>> 0,
        str: msg.str >>> 0,
        dex: msg.dex >>> 0,
        intStat: msg.intStat >>> 0,
        luk: msg.luk >>> 0,
        hp: msg.hp >>> 0,
        maxHp: msg.maxHp >>> 0,
        mp: msg.mp >>> 0,
        maxMp: msg.maxMp >>> 0,
        abilityPoint: msg.abilityPoint >>> 0,
        exp: msg.exp >>> 0,
        mapId: msg.mapId >>> 0,
        spawnPoint: msg.spawnPoint >>> 0,
        positionX: msg.positionX | 0,
        positionY: msg.positionY | 0,
        stance: msg.stance >>> 0,
        meso: msg.meso | 0,
        skillPoint: msg.skillPoint >>> 0,
        accountId: msg.accountId >>> 0,
        hidden: Boolean(msg.hidden),
    };
}
